services:
  api:
    container_name: api-selecao
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn typeorm migration:run && yarn dev'
  pg:
    container_name: postgresContele
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
